services:
  ssd-exam-project:
    image: ssd-exam-project
    build:
      context: .
      dockerfile: SSD-Exam-Project/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=taskdb;Username=taskuser;Password=password
    ports:
      - "5021:8080"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=taskuser
      - POSTGRES_DB=taskdb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U taskuser" ]
      interval: 10s
      timeout: 5s
      retries: 5